// regisform
export const INPUT_TEXT = 'INPUT_TEXT';
export const ON_REGISTER_PARENT = 'ON_REGISTER_PARENT';
export const CHEKCED_TERMS_REGISTER = 'CHEKCED_TERMS_REGISTER';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';


// Login Form
export const LOGIN_NIM_CHANGED = 'LOGIN_NIM_CHANGED';
export const LOGIN_USERNAME_CHANGED = 'LOGIN_USERNAME_CHANGED';
export const LOGIN_PASSWORD_CHANGED = 'LOGIN_PASSWORD_CHANGED';
export const HIDE_UNHIDE = 'HIDE_UNHIDE';
export const ON_USER_LOGIN = 'ON_USER_LOGIN';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

//user 
export const LOGOUT_USER = 'LOGOUT_USER';

//profile
export const INIT_PROFILE_IMAGE = 'INIT_PROFILE_IMAGE'

//DETAL_murid
export const DETAIL_NIM_SELECT = 'DETAIL_NIM_SELECT'

//produc page
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS'
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS'
export const GET_TRANSACTION_SUCCESS = 'GET_TRANSACTION_SUCCESS'
export const INPUT_SEARCH = 'INPUT_SEARCH'
export const GET_PRODUCT_SEARCH_SUCCESS = 'GET_PRODUCT_SEARCH_SUCCESS'

//getDataadmin
export const GET_PARENT_SUCCESS = 'GET_PARENT_SUCCESS'
export const GET_STUDENT_SUCCESS = 'GET_STUDENT_SUCCESS'
// export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'

//adminpage
export const INPUT_EDIT_TEXT = 'INPUT_EDIT_TEXT'
export const EDIT_FAILED = 'EDIT_FAILED'
export const EDIT_SUCCESS = 'EDIT_SUCCESS'

//addStudent reducer
export const REGISTER_MURID_SUCCESS = 'REGISTER_MURID_SUCCESS'
export const REGISTER_MURID_FAILED = 'REGISTER_MURID_FAILED'
export const INPUT_ADD_MURID_TEXT = 'INPUT_ADD_MURID_TEXT'


//category reducer
export const GET_PRODUCT_CATEGORY_SUCCESS = 'GET_PRODUCT_CATEGORY_SUCCESS'
export const SELECTED_CATEGORY = 'SELECTED_CATEGORY'
