// regisform
export const INPUT_TEXT = 'INPUT_TEXT';
export const ON_REGISTER_PARENT = 'ON_REGISTER_PARENT';
export const CHEKCED_TERMS_REGISTER = 'CHEKCED_TERMS_REGISTER';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';


// Login Form
export const LOGIN_NIM_CHANGED = 'LOGIN_NIM_CHANGED';
export const LOGIN_USERNAME_CHANGED = 'LOGIN_USERNAME_CHANGED';
export const LOGIN_PASSWORD_CHANGED = 'LOGIN_PASSWORD_CHANGED';
export const HIDE_UNHIDE = 'HIDE_UNHIDE';
export const ON_USER_LOGIN = 'ON_USER_LOGIN';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

//user 
export const LOGOUT_USER = 'LOGOUT_USER';

//profile
export const INIT_PROFILE_IMAGE = 'INIT_PROFILE_IMAGE'

//DETAL_murid
export const DETAIL_NIM_SELECT = 'DETAIL_NIM_SELECT'